[package]
name = "rust_caster"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "raycaster",
]

[dependencies]
raycaster = { path = "raycaster" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"